// react/src/components/shared/FooterComponent.tsx
import { Sparkles } from "lucide-react";
import { Link } from "react-router";
import { IconGithub } from "../icons/IconGithub";
import { IconInstagram } from "../icons/IconInstagram";
import { IconLinkedin } from "../icons/IconLinkedin";

export default function FooterComponent() {
    return <footer className="border-t bg-muted/40 px-4 md:px-8">
    <div className="container flex flex-col md:flex-row justify-between items-center py-10 gap-6">
      <div className="flex items-center gap-2">
        <Sparkles className="h-6 w-6 text-primary" />
        <span className="text-xl font-bold">Codebox</span>
      </div>

      <div className="flex flex-col md:flex-row items-center gap-6 md:gap-10">
        <nav className="flex flex-wrap justify-center gap-6">
          <Link to="#" className="text-sm text-muted-foreground hover:text-foreground">
            About
          </Link>
          <Link to="#" className="text-sm text-muted-foreground hover:text-foreground">
            Components
          </Link>
          <Link to="#" className="text-sm text-muted-foreground hover:text-foreground">
            Challenges
          </Link>
          <Link to="#" className="text-sm text-muted-foreground hover:text-foreground">
            Creators
          </Link>
        </nav>

        <div className="flex items-center gap-4">
          <button className="btn btn-sm btn-ghost btn-circle">
            <IconGithub className="h-5 w-5" />
          </button>
          <button className="btn btn-sm btn-ghost btn-circle">
            <IconInstagram className="h-5 w-5" />
          </button>
          <button className="btn btn-sm btn-ghost btn-circle">
            <IconLinkedin className="h-5 w-5" />
          </button>
        </div>
      </div>

      <div className="text-sm text-muted-foreground">© 2025 Codebox. All rights reserved.</div>
    </div>
  </footer>;
}

// vue/src/components/shared/FooterComponent.vue
<template>
  <footer class="border-t bg-muted/40 px-4 md:px-8">
    <div class="container flex flex-col md:flex-row justify-between items-center py-10 gap-6">
      <div class="flex items-center gap-2">
        <Sparkles class="h-6 w-6 text-primary" />
        <span class="text-xl font-bold">ComponentVerse</span>
      </div>

      <div class="flex flex-col md:flex-row items-center gap-6 md:gap-10">
        <nav class="flex flex-wrap justify-center gap-6">
          <router-link to="#" class="text-sm text-muted-foreground hover:text-foreground">
            About
          </router-link>
          <router-link to="#" class="text-sm text-muted-foreground hover:text-foreground">
            Components
          </router-link>
          <router-link to="#" class="text-sm text-muted-foreground hover:text-foreground">
            Challenges
          </router-link>
          <router-link to="#" class="text-sm text-muted-foreground hover:text-foreground">
            Creators
          </router-link>
        </nav>

        <div class="flex items-center gap-4">
          <button type="button" class="btn btn-sm btn-ghost btn-circle">
            <IconGithub class="h-5 w-5" />
          </button>
          <button type="button" class="btn btn-sm btn-ghost btn-circle">
            <IconInstagram class="h-5 w-5" />
          </button>
          <button type="button" class="btn btn-sm btn-ghost btn-circle">
            <IconLinkedin class="h-5 w-5" />
          </button>
        </div>
      </div>

      <div class="text-sm text-muted-foreground">© 2025 Codebox. All rights reserved.</div>
    </div>
  </footer>
</template>
<script setup lang="ts">
import IconGithub from "@/components/icons/IconGithub.vue";
import IconInstagram from "@/components/icons/IconInstagram.vue";
import IconLinkedin from "@/components/icons/IconLinkedin.vue";
import { Sparkles } from "lucide-vue-next";
</script>
