// vue/src/components/shared/ModalComponent.vue
<template>
  <dialog id="my_modal_1" class="modal">
    <div class="modal-box border border-white/20">
      <h3 class="text-lg font-bold">{{ title }}</h3>
      <slot></slot>
      <div class="modal-action">
        <form method="dialog">
          <!-- if there is a button in form, it will close the modal -->
          <button type="button" @click="close" class="btn btn-primary">Accept</button>
        </form>
      </div>
    </div>
  </dialog>
</template>
<script setup lang="ts">
defineProps({
  title: String,
  text: String,
});
const emits = defineEmits(["close"]);

const close = () => emits("close");
</script>

// react/src/components/shared/ModalComponent.tsx

interface Props {
    title: string
    close: () => void
    children: React.ReactNode
}
export default function ModalComponent({ title, close, children }: Props) {
    return <dialog id="my_modal_1" className="modal">
    <div className="modal-box border border-white/20">
      <h3 className="text-lg font-bold">{ title }</h3>
      {children}
      <div className="modal-action">
        <form method="dialog">
          <button onClick={close} className="btn btn-primary">Accept</button>
        </form>
      </div>
    </div>
  </dialog>;
}
